// Code generated by ogen, DO NOT EDIT.

package openapi

import (
	"fmt"
	"io"
	"time"

	"github.com/go-faster/errors"
	"github.com/google/uuid"
)

func (s *ErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

type AddCollectionReq struct {
	Name        string    `json:"name"`
	Description OptString `json:"description"`
}

// GetName returns the value of Name.
func (s *AddCollectionReq) GetName() string {
	return s.Name
}

// GetDescription returns the value of Description.
func (s *AddCollectionReq) GetDescription() OptString {
	return s.Description
}

// SetName sets the value of Name.
func (s *AddCollectionReq) SetName(val string) {
	s.Name = val
}

// SetDescription sets the value of Description.
func (s *AddCollectionReq) SetDescription(val OptString) {
	s.Description = val
}

type AddPageBadRequest struct {
	Field string `json:"field"`
	Error string `json:"error"`
}

// GetField returns the value of Field.
func (s *AddPageBadRequest) GetField() string {
	return s.Field
}

// GetError returns the value of Error.
func (s *AddPageBadRequest) GetError() string {
	return s.Error
}

// SetField sets the value of Field.
func (s *AddPageBadRequest) SetField(val string) {
	s.Field = val
}

// SetError sets the value of Error.
func (s *AddPageBadRequest) SetError(val string) {
	s.Error = val
}

func (*AddPageBadRequest) addPageRes() {}

type AddPageReq struct {
	URL          string     `json:"url"`
	Description  OptString  `json:"description"`
	Formats      []Format   `json:"formats"`
	Tags         []string   `json:"tags"`
	CollectionID OptNilUUID `json:"collection_id"`
	// Note: link depth > 1 might cause large archives.
	Depth   OptInt               `json:"depth"`
	Headers OptAddPageReqHeaders `json:"headers"`
	Cookies OptAddPageReqCookies `json:"cookies"`
}

// GetURL returns the value of URL.
func (s *AddPageReq) GetURL() string {
	return s.URL
}

// GetDescription returns the value of Description.
func (s *AddPageReq) GetDescription() OptString {
	return s.Description
}

// GetFormats returns the value of Formats.
func (s *AddPageReq) GetFormats() []Format {
	return s.Formats
}

// GetTags returns the value of Tags.
func (s *AddPageReq) GetTags() []string {
	return s.Tags
}

// GetCollectionID returns the value of CollectionID.
func (s *AddPageReq) GetCollectionID() OptNilUUID {
	return s.CollectionID
}

// GetDepth returns the value of Depth.
func (s *AddPageReq) GetDepth() OptInt {
	return s.Depth
}

// GetHeaders returns the value of Headers.
func (s *AddPageReq) GetHeaders() OptAddPageReqHeaders {
	return s.Headers
}

// GetCookies returns the value of Cookies.
func (s *AddPageReq) GetCookies() OptAddPageReqCookies {
	return s.Cookies
}

// SetURL sets the value of URL.
func (s *AddPageReq) SetURL(val string) {
	s.URL = val
}

// SetDescription sets the value of Description.
func (s *AddPageReq) SetDescription(val OptString) {
	s.Description = val
}

// SetFormats sets the value of Formats.
func (s *AddPageReq) SetFormats(val []Format) {
	s.Formats = val
}

// SetTags sets the value of Tags.
func (s *AddPageReq) SetTags(val []string) {
	s.Tags = val
}

// SetCollectionID sets the value of CollectionID.
func (s *AddPageReq) SetCollectionID(val OptNilUUID) {
	s.CollectionID = val
}

// SetDepth sets the value of Depth.
func (s *AddPageReq) SetDepth(val OptInt) {
	s.Depth = val
}

// SetHeaders sets the value of Headers.
func (s *AddPageReq) SetHeaders(val OptAddPageReqHeaders) {
	s.Headers = val
}

// SetCookies sets the value of Cookies.
func (s *AddPageReq) SetCookies(val OptAddPageReqCookies) {
	s.Cookies = val
}

type AddPageReqCookies map[string]string

func (s *AddPageReqCookies) init() AddPageReqCookies {
	m := *s
	if m == nil {
		m = map[string]string{}
		*s = m
	}
	return m
}

type AddPageReqHeaders map[string]string

func (s *AddPageReqHeaders) init() AddPageReqHeaders {
	m := *s
	if m == nil {
		m = map[string]string{}
		*s = m
	}
	return m
}

// Ref: #/components/schemas/collection
type Collection struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description OptString `json:"description"`
	Created     time.Time `json:"created"`
}

// GetID returns the value of ID.
func (s *Collection) GetID() uuid.UUID {
	return s.ID
}

// GetName returns the value of Name.
func (s *Collection) GetName() string {
	return s.Name
}

// GetDescription returns the value of Description.
func (s *Collection) GetDescription() OptString {
	return s.Description
}

// GetCreated returns the value of Created.
func (s *Collection) GetCreated() time.Time {
	return s.Created
}

// SetID sets the value of ID.
func (s *Collection) SetID(val uuid.UUID) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *Collection) SetName(val string) {
	s.Name = val
}

// SetDescription sets the value of Description.
func (s *Collection) SetDescription(val OptString) {
	s.Description = val
}

// SetCreated sets the value of Created.
func (s *Collection) SetCreated(val time.Time) {
	s.Created = val
}

func (*Collection) getCollectionRes() {}

// DeleteCollectionNoContent is response for DeleteCollection operation.
type DeleteCollectionNoContent struct{}

func (*DeleteCollectionNoContent) deleteCollectionRes() {}

// DeleteCollectionNotFound is response for DeleteCollection operation.
type DeleteCollectionNotFound struct{}

func (*DeleteCollectionNotFound) deleteCollectionRes() {}

// DeletePageNoContent is response for DeletePage operation.
type DeletePageNoContent struct{}

func (*DeletePageNoContent) deletePageRes() {}

// DeletePageNotFound is response for DeletePage operation.
type DeletePageNotFound struct{}

func (*DeletePageNotFound) deletePageRes() {}

// Ref: #/components/schemas/error
type Error struct {
	Message   string    `json:"message"`
	Localized OptString `json:"localized"`
}

// GetMessage returns the value of Message.
func (s *Error) GetMessage() string {
	return s.Message
}

// GetLocalized returns the value of Localized.
func (s *Error) GetLocalized() OptString {
	return s.Localized
}

// SetMessage sets the value of Message.
func (s *Error) SetMessage(val string) {
	s.Message = val
}

// SetLocalized sets the value of Localized.
func (s *Error) SetLocalized(val OptString) {
	s.Localized = val
}

// ErrorStatusCode wraps Error with StatusCode.
type ErrorStatusCode struct {
	StatusCode int
	Response   Error
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorStatusCode) GetResponse() Error {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorStatusCode) SetResponse(val Error) {
	s.Response = val
}

// Ref: #/components/schemas/format
type Format string

const (
	FormatAll        Format = "all"
	FormatPdf        Format = "pdf"
	FormatSingleFile Format = "single_file"
	FormatHeaders    Format = "headers"
	FormatMarkdown   Format = "markdown"
)

// AllValues returns all Format values.
func (Format) AllValues() []Format {
	return []Format{
		FormatAll,
		FormatPdf,
		FormatSingleFile,
		FormatHeaders,
		FormatMarkdown,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s Format) MarshalText() ([]byte, error) {
	switch s {
	case FormatAll:
		return []byte(s), nil
	case FormatPdf:
		return []byte(s), nil
	case FormatSingleFile:
		return []byte(s), nil
	case FormatHeaders:
		return []byte(s), nil
	case FormatMarkdown:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *Format) UnmarshalText(data []byte) error {
	switch Format(data) {
	case FormatAll:
		*s = FormatAll
		return nil
	case FormatPdf:
		*s = FormatPdf
		return nil
	case FormatSingleFile:
		*s = FormatSingleFile
		return nil
	case FormatHeaders:
		*s = FormatHeaders
		return nil
	case FormatMarkdown:
		*s = FormatMarkdown
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// GetCollectionNotFound is response for GetCollection operation.
type GetCollectionNotFound struct{}

func (*GetCollectionNotFound) getCollectionRes() {}

// GetFileNotFound is response for GetFile operation.
type GetFileNotFound struct{}

func (*GetFileNotFound) getFileRes() {}

type GetFileOKApplicationPdf struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetFileOKApplicationPdf) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetFileOKApplicationPdf) getFileRes() {}

type GetFileOKTextHTMLCharsetUtf8 struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetFileOKTextHTMLCharsetUtf8) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetFileOKTextHTMLCharsetUtf8) getFileRes() {}

type GetFileOKTextPlainCharsetUtf8 struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetFileOKTextPlainCharsetUtf8) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetFileOKTextPlainCharsetUtf8) getFileRes() {}

// GetPageNotFound is response for GetPage operation.
type GetPageNotFound struct{}

func (*GetPageNotFound) getPageRes() {}

// NewOptAddCollectionReq returns new OptAddCollectionReq with value set to v.
func NewOptAddCollectionReq(v AddCollectionReq) OptAddCollectionReq {
	return OptAddCollectionReq{
		Value: v,
		Set:   true,
	}
}

// OptAddCollectionReq is optional AddCollectionReq.
type OptAddCollectionReq struct {
	Value AddCollectionReq
	Set   bool
}

// IsSet returns true if OptAddCollectionReq was set.
func (o OptAddCollectionReq) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptAddCollectionReq) Reset() {
	var v AddCollectionReq
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptAddCollectionReq) SetTo(v AddCollectionReq) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptAddCollectionReq) Get() (v AddCollectionReq, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptAddCollectionReq) Or(d AddCollectionReq) AddCollectionReq {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptAddPageReq returns new OptAddPageReq with value set to v.
func NewOptAddPageReq(v AddPageReq) OptAddPageReq {
	return OptAddPageReq{
		Value: v,
		Set:   true,
	}
}

// OptAddPageReq is optional AddPageReq.
type OptAddPageReq struct {
	Value AddPageReq
	Set   bool
}

// IsSet returns true if OptAddPageReq was set.
func (o OptAddPageReq) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptAddPageReq) Reset() {
	var v AddPageReq
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptAddPageReq) SetTo(v AddPageReq) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptAddPageReq) Get() (v AddPageReq, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptAddPageReq) Or(d AddPageReq) AddPageReq {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptAddPageReqCookies returns new OptAddPageReqCookies with value set to v.
func NewOptAddPageReqCookies(v AddPageReqCookies) OptAddPageReqCookies {
	return OptAddPageReqCookies{
		Value: v,
		Set:   true,
	}
}

// OptAddPageReqCookies is optional AddPageReqCookies.
type OptAddPageReqCookies struct {
	Value AddPageReqCookies
	Set   bool
}

// IsSet returns true if OptAddPageReqCookies was set.
func (o OptAddPageReqCookies) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptAddPageReqCookies) Reset() {
	var v AddPageReqCookies
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptAddPageReqCookies) SetTo(v AddPageReqCookies) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptAddPageReqCookies) Get() (v AddPageReqCookies, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptAddPageReqCookies) Or(d AddPageReqCookies) AddPageReqCookies {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptAddPageReqHeaders returns new OptAddPageReqHeaders with value set to v.
func NewOptAddPageReqHeaders(v AddPageReqHeaders) OptAddPageReqHeaders {
	return OptAddPageReqHeaders{
		Value: v,
		Set:   true,
	}
}

// OptAddPageReqHeaders is optional AddPageReqHeaders.
type OptAddPageReqHeaders struct {
	Value AddPageReqHeaders
	Set   bool
}

// IsSet returns true if OptAddPageReqHeaders was set.
func (o OptAddPageReqHeaders) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptAddPageReqHeaders) Reset() {
	var v AddPageReqHeaders
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptAddPageReqHeaders) SetTo(v AddPageReqHeaders) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptAddPageReqHeaders) Get() (v AddPageReqHeaders, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptAddPageReqHeaders) Or(d AddPageReqHeaders) AddPageReqHeaders {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilUUID returns new OptNilUUID with value set to v.
func NewOptNilUUID(v uuid.UUID) OptNilUUID {
	return OptNilUUID{
		Value: v,
		Set:   true,
	}
}

// OptNilUUID is optional nullable uuid.UUID.
type OptNilUUID struct {
	Value uuid.UUID
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilUUID was set.
func (o OptNilUUID) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilUUID) Reset() {
	var v uuid.UUID
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilUUID) SetTo(v uuid.UUID) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsSet returns true if value is Null.
func (o OptNilUUID) IsNull() bool { return o.Null }

// SetNull sets value to null.
func (o *OptNilUUID) SetToNull() {
	o.Set = true
	o.Null = true
	var v uuid.UUID
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilUUID) Get() (v uuid.UUID, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilUUID) Or(d uuid.UUID) uuid.UUID {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUpdatePageReq returns new OptUpdatePageReq with value set to v.
func NewOptUpdatePageReq(v UpdatePageReq) OptUpdatePageReq {
	return OptUpdatePageReq{
		Value: v,
		Set:   true,
	}
}

// OptUpdatePageReq is optional UpdatePageReq.
type OptUpdatePageReq struct {
	Value UpdatePageReq
	Set   bool
}

// IsSet returns true if OptUpdatePageReq was set.
func (o OptUpdatePageReq) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUpdatePageReq) Reset() {
	var v UpdatePageReq
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUpdatePageReq) SetTo(v UpdatePageReq) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUpdatePageReq) Get() (v UpdatePageReq, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUpdatePageReq) Or(d UpdatePageReq) UpdatePageReq {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/page
type Page struct {
	ID           uuid.UUID  `json:"id"`
	URL          string     `json:"url"`
	Created      time.Time  `json:"created"`
	CollectionID OptNilUUID `json:"collection_id"`
	Depth        int        `json:"depth"`
	Formats      []Format   `json:"formats"`
	Tags         []string   `json:"tags"`
	Status       Status     `json:"status"`
	Meta         PageMeta   `json:"meta"`
}

// GetID returns the value of ID.
func (s *Page) GetID() uuid.UUID {
	return s.ID
}

// GetURL returns the value of URL.
func (s *Page) GetURL() string {
	return s.URL
}

// GetCreated returns the value of Created.
func (s *Page) GetCreated() time.Time {
	return s.Created
}

// GetCollectionID returns the value of CollectionID.
func (s *Page) GetCollectionID() OptNilUUID {
	return s.CollectionID
}

// GetDepth returns the value of Depth.
func (s *Page) GetDepth() int {
	return s.Depth
}

// GetFormats returns the value of Formats.
func (s *Page) GetFormats() []Format {
	return s.Formats
}

// GetTags returns the value of Tags.
func (s *Page) GetTags() []string {
	return s.Tags
}

// GetStatus returns the value of Status.
func (s *Page) GetStatus() Status {
	return s.Status
}

// GetMeta returns the value of Meta.
func (s *Page) GetMeta() PageMeta {
	return s.Meta
}

// SetID sets the value of ID.
func (s *Page) SetID(val uuid.UUID) {
	s.ID = val
}

// SetURL sets the value of URL.
func (s *Page) SetURL(val string) {
	s.URL = val
}

// SetCreated sets the value of Created.
func (s *Page) SetCreated(val time.Time) {
	s.Created = val
}

// SetCollectionID sets the value of CollectionID.
func (s *Page) SetCollectionID(val OptNilUUID) {
	s.CollectionID = val
}

// SetDepth sets the value of Depth.
func (s *Page) SetDepth(val int) {
	s.Depth = val
}

// SetFormats sets the value of Formats.
func (s *Page) SetFormats(val []Format) {
	s.Formats = val
}

// SetTags sets the value of Tags.
func (s *Page) SetTags(val []string) {
	s.Tags = val
}

// SetStatus sets the value of Status.
func (s *Page) SetStatus(val Status) {
	s.Status = val
}

// SetMeta sets the value of Meta.
func (s *Page) SetMeta(val PageMeta) {
	s.Meta = val
}

func (*Page) addPageRes()    {}
func (*Page) updatePageRes() {}

type PageMeta struct {
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Error       OptString `json:"error"`
}

// GetTitle returns the value of Title.
func (s *PageMeta) GetTitle() string {
	return s.Title
}

// GetDescription returns the value of Description.
func (s *PageMeta) GetDescription() string {
	return s.Description
}

// GetError returns the value of Error.
func (s *PageMeta) GetError() OptString {
	return s.Error
}

// SetTitle sets the value of Title.
func (s *PageMeta) SetTitle(val string) {
	s.Title = val
}

// SetDescription sets the value of Description.
func (s *PageMeta) SetDescription(val string) {
	s.Description = val
}

// SetError sets the value of Error.
func (s *PageMeta) SetError(val OptString) {
	s.Error = val
}

// Merged schema.
// Ref: #/components/schemas/pageWithResults
type PageWithResults struct {
	ID           uuid.UUID           `json:"id"`
	URL          string              `json:"url"`
	Created      time.Time           `json:"created"`
	CollectionID OptNilUUID          `json:"collection_id"`
	Depth        int                 `json:"depth"`
	Formats      []Format            `json:"formats"`
	Tags         []string            `json:"tags"`
	Status       Status              `json:"status"`
	Meta         PageWithResultsMeta `json:"meta"`
	Results      []Result            `json:"results"`
}

// GetID returns the value of ID.
func (s *PageWithResults) GetID() uuid.UUID {
	return s.ID
}

// GetURL returns the value of URL.
func (s *PageWithResults) GetURL() string {
	return s.URL
}

// GetCreated returns the value of Created.
func (s *PageWithResults) GetCreated() time.Time {
	return s.Created
}

// GetCollectionID returns the value of CollectionID.
func (s *PageWithResults) GetCollectionID() OptNilUUID {
	return s.CollectionID
}

// GetDepth returns the value of Depth.
func (s *PageWithResults) GetDepth() int {
	return s.Depth
}

// GetFormats returns the value of Formats.
func (s *PageWithResults) GetFormats() []Format {
	return s.Formats
}

// GetTags returns the value of Tags.
func (s *PageWithResults) GetTags() []string {
	return s.Tags
}

// GetStatus returns the value of Status.
func (s *PageWithResults) GetStatus() Status {
	return s.Status
}

// GetMeta returns the value of Meta.
func (s *PageWithResults) GetMeta() PageWithResultsMeta {
	return s.Meta
}

// GetResults returns the value of Results.
func (s *PageWithResults) GetResults() []Result {
	return s.Results
}

// SetID sets the value of ID.
func (s *PageWithResults) SetID(val uuid.UUID) {
	s.ID = val
}

// SetURL sets the value of URL.
func (s *PageWithResults) SetURL(val string) {
	s.URL = val
}

// SetCreated sets the value of Created.
func (s *PageWithResults) SetCreated(val time.Time) {
	s.Created = val
}

// SetCollectionID sets the value of CollectionID.
func (s *PageWithResults) SetCollectionID(val OptNilUUID) {
	s.CollectionID = val
}

// SetDepth sets the value of Depth.
func (s *PageWithResults) SetDepth(val int) {
	s.Depth = val
}

// SetFormats sets the value of Formats.
func (s *PageWithResults) SetFormats(val []Format) {
	s.Formats = val
}

// SetTags sets the value of Tags.
func (s *PageWithResults) SetTags(val []string) {
	s.Tags = val
}

// SetStatus sets the value of Status.
func (s *PageWithResults) SetStatus(val Status) {
	s.Status = val
}

// SetMeta sets the value of Meta.
func (s *PageWithResults) SetMeta(val PageWithResultsMeta) {
	s.Meta = val
}

// SetResults sets the value of Results.
func (s *PageWithResults) SetResults(val []Result) {
	s.Results = val
}

func (*PageWithResults) getPageRes() {}

type PageWithResultsMeta struct {
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Error       OptString `json:"error"`
}

// GetTitle returns the value of Title.
func (s *PageWithResultsMeta) GetTitle() string {
	return s.Title
}

// GetDescription returns the value of Description.
func (s *PageWithResultsMeta) GetDescription() string {
	return s.Description
}

// GetError returns the value of Error.
func (s *PageWithResultsMeta) GetError() OptString {
	return s.Error
}

// SetTitle sets the value of Title.
func (s *PageWithResultsMeta) SetTitle(val string) {
	s.Title = val
}

// SetDescription sets the value of Description.
func (s *PageWithResultsMeta) SetDescription(val string) {
	s.Description = val
}

// SetError sets the value of Error.
func (s *PageWithResultsMeta) SetError(val OptString) {
	s.Error = val
}

type Pages []Page

// Ref: #/components/schemas/result
type Result struct {
	Format Format            `json:"format"`
	Error  OptString         `json:"error"`
	Files  []ResultFilesItem `json:"files"`
}

// GetFormat returns the value of Format.
func (s *Result) GetFormat() Format {
	return s.Format
}

// GetError returns the value of Error.
func (s *Result) GetError() OptString {
	return s.Error
}

// GetFiles returns the value of Files.
func (s *Result) GetFiles() []ResultFilesItem {
	return s.Files
}

// SetFormat sets the value of Format.
func (s *Result) SetFormat(val Format) {
	s.Format = val
}

// SetError sets the value of Error.
func (s *Result) SetError(val OptString) {
	s.Error = val
}

// SetFiles sets the value of Files.
func (s *Result) SetFiles(val []ResultFilesItem) {
	s.Files = val
}

type ResultFilesItem struct {
	ID       uuid.UUID `json:"id"`
	Name     string    `json:"name"`
	Mimetype string    `json:"mimetype"`
	Size     int64     `json:"size"`
}

// GetID returns the value of ID.
func (s *ResultFilesItem) GetID() uuid.UUID {
	return s.ID
}

// GetName returns the value of Name.
func (s *ResultFilesItem) GetName() string {
	return s.Name
}

// GetMimetype returns the value of Mimetype.
func (s *ResultFilesItem) GetMimetype() string {
	return s.Mimetype
}

// GetSize returns the value of Size.
func (s *ResultFilesItem) GetSize() int64 {
	return s.Size
}

// SetID sets the value of ID.
func (s *ResultFilesItem) SetID(val uuid.UUID) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *ResultFilesItem) SetName(val string) {
	s.Name = val
}

// SetMimetype sets the value of Mimetype.
func (s *ResultFilesItem) SetMimetype(val string) {
	s.Mimetype = val
}

// SetSize sets the value of Size.
func (s *ResultFilesItem) SetSize(val int64) {
	s.Size = val
}

// Ref: #/components/schemas/status
type Status string

const (
	StatusNew        Status = "new"
	StatusProcessing Status = "processing"
	StatusDone       Status = "done"
	StatusFailed     Status = "failed"
	StatusWithErrors Status = "with_errors"
)

// AllValues returns all Status values.
func (Status) AllValues() []Status {
	return []Status{
		StatusNew,
		StatusProcessing,
		StatusDone,
		StatusFailed,
		StatusWithErrors,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s Status) MarshalText() ([]byte, error) {
	switch s {
	case StatusNew:
		return []byte(s), nil
	case StatusProcessing:
		return []byte(s), nil
	case StatusDone:
		return []byte(s), nil
	case StatusFailed:
		return []byte(s), nil
	case StatusWithErrors:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *Status) UnmarshalText(data []byte) error {
	switch Status(data) {
	case StatusNew:
		*s = StatusNew
		return nil
	case StatusProcessing:
		*s = StatusProcessing
		return nil
	case StatusDone:
		*s = StatusDone
		return nil
	case StatusFailed:
		*s = StatusFailed
		return nil
	case StatusWithErrors:
		*s = StatusWithErrors
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// UpdatePageNotFound is response for UpdatePage operation.
type UpdatePageNotFound struct{}

func (*UpdatePageNotFound) updatePageRes() {}

type UpdatePageReq struct {
	Title       OptString `json:"title"`
	Description OptString `json:"description"`
	Tags        []string  `json:"tags"`
}

// GetTitle returns the value of Title.
func (s *UpdatePageReq) GetTitle() OptString {
	return s.Title
}

// GetDescription returns the value of Description.
func (s *UpdatePageReq) GetDescription() OptString {
	return s.Description
}

// GetTags returns the value of Tags.
func (s *UpdatePageReq) GetTags() []string {
	return s.Tags
}

// SetTitle sets the value of Title.
func (s *UpdatePageReq) SetTitle(val OptString) {
	s.Title = val
}

// SetDescription sets the value of Description.
func (s *UpdatePageReq) SetDescription(val OptString) {
	s.Description = val
}

// SetTags sets the value of Tags.
func (s *UpdatePageReq) SetTags(val []string) {
	s.Tags = val
}
