// Code generated by ogen, DO NOT EDIT.

package openapi

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// AddCollection implements addCollection operation.
//
// Add new collection.
//
// POST /collections
func (UnimplementedHandler) AddCollection(ctx context.Context, req OptAddCollectionReq) (r *Collection, _ error) {
	return r, ht.ErrNotImplemented
}

// AddPage implements addPage operation.
//
// Add new page.
//
// POST /pages
func (UnimplementedHandler) AddPage(ctx context.Context, req OptAddPageReq, params AddPageParams) (r AddPageRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteCollection implements deleteCollection operation.
//
// Delete a collection.
//
// DELETE /collections/{id}
func (UnimplementedHandler) DeleteCollection(ctx context.Context, params DeleteCollectionParams) (r DeleteCollectionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeletePage implements deletePage operation.
//
// Delete a page and its files.
//
// DELETE /pages/{id}
func (UnimplementedHandler) DeletePage(ctx context.Context, params DeletePageParams) (r DeletePageRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCollection implements getCollection operation.
//
// Get collection details.
//
// GET /collections/{id}
func (UnimplementedHandler) GetCollection(ctx context.Context, params GetCollectionParams) (r GetCollectionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCollections implements getCollections operation.
//
// Get all collections.
//
// GET /collections
func (UnimplementedHandler) GetCollections(ctx context.Context) (r []Collection, _ error) {
	return r, ht.ErrNotImplemented
}

// GetFile implements getFile operation.
//
// Get file content.
//
// GET /pages/{id}/file/{file_id}
func (UnimplementedHandler) GetFile(ctx context.Context, params GetFileParams) (r GetFileRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPage implements getPage operation.
//
// Get page details.
//
// GET /pages/{id}
func (UnimplementedHandler) GetPage(ctx context.Context, params GetPageParams) (r GetPageRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPages implements getPages operation.
//
// Get all pages.
//
// GET /pages
func (UnimplementedHandler) GetPages(ctx context.Context, params GetPagesParams) (r Pages, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdatePage implements updatePage operation.
//
// Edit page details (title, description, tags).
//
// PATCH /pages/{id}
func (UnimplementedHandler) UpdatePage(ctx context.Context, req OptUpdatePageReq, params UpdatePageParams) (r UpdatePageRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
