// Code generated by ogen, DO NOT EDIT.
package openapi

type AddPageRes interface {
	addPageRes()
}

type DeletePageRes interface {
	deletePageRes()
}

type GetFileRes interface {
	getFileRes()
}

type GetPageRes interface {
	getPageRes()
}

type UpdatePageRes interface {
	updatePageRes()
}
