// Code generated by ogen, DO NOT EDIT.
package openapi

type AddPageRes interface {
	addPageRes()
}

type DeleteCollectionRes interface {
	deleteCollectionRes()
}

type DeletePageRes interface {
	deletePageRes()
}

type GetCollectionRes interface {
	getCollectionRes()
}

type GetFileRes interface {
	getFileRes()
}

type GetPageRes interface {
	getPageRes()
}

type UpdatePageRes interface {
	updatePageRes()
}
